version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - USER_NAME=${USER_NAME:-ec2-user}
        - GID=${GID:-1000}
        - GROUP_NAME=${GROUP_NAME:-ec2-user}

    platform: linux/amd64
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/:/var/www
    networks:
      - app-network
    expose:
      - 9000

  #Nginx Service
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./src/:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
